// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-zSOnIb3NwKBfongOIEINgwp51hw1fSA',
    appId: '1:302877325278:web:bde42d1e28e34e978a0f4f',
    messagingSenderId: '302877325278',
    projectId: 'test-fe328',
    authDomain: 'test-fe328.firebaseapp.com',
    storageBucket: 'test-fe328.appspot.com',
    measurementId: 'G-Z2MHGJZ1Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwbmQWKKU319g34P-3ZmPXpA4dEDcKYaY',
    appId: '1:302877325278:android:cb2763e8d31d25808a0f4f',
    messagingSenderId: '302877325278',
    projectId: 'test-fe328',
    storageBucket: 'test-fe328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8zLhdqodzxjOjOeiFZhf1Vm67BjNaQ-Q',
    appId: '1:302877325278:ios:1171fae06798d8068a0f4f',
    messagingSenderId: '302877325278',
    projectId: 'test-fe328',
    storageBucket: 'test-fe328.appspot.com',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8zLhdqodzxjOjOeiFZhf1Vm67BjNaQ-Q',
    appId: '1:302877325278:ios:1171fae06798d8068a0f4f',
    messagingSenderId: '302877325278',
    projectId: 'test-fe328',
    storageBucket: 'test-fe328.appspot.com',
    iosBundleId: 'com.example.myFlutterProject',
  );
}
